# Generated by Django 3.0.2 on 2020-12-09 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='temp',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
