# Generated by Django 3.0.2 on 2020-12-09 09:13

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='temp',
            field=models.FileField(upload_to=blogs.models.user_directory_path),
        ),
    ]
