# Generated by Django 3.0.2 on 2020-12-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20201209_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='temp',
        ),
        migrations.AddField(
            model_name='blog',
            name='upload',
            field=models.FileField(default='', upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
