# Generated by Django 3.0.2 on 2020-12-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20201209_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='upload',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
