# Generated by Django 2.1.15 on 2021-03-02 08:55

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_contentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
