# Generated by Django 2.1.15 on 2021-03-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20210302_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='upload',
            field=models.FileField(blank=True, upload_to='blogs/uploads/%Y/%m/%d/'),
        ),
    ]
