# Generated by Django 2.1.15 on 2021-03-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20210306_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blogs.Category'),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blogs.Blog'),
        ),
    ]
